name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.14
      - run: go version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Examine source code for Linux AMD
        run: GOOS=linux GOARCH=amd64 go vet -v ./...

      - name: Examine source code for MacOS AMD
        run: GOOS=darwin GOARCH=amd64 go vet -v ./...

      - name: Examine source code for Windows AMD
        run: GOOS=windows GOARCH=amd64 go vet -v ./...

      - name: Examine source code for Linux ARM
        run: GOOS=linux GOARCH=arm64 go vet -v ./...

      - name: Examine source code for MacOS ARM
        run: GOOS=darwin GOARCH=arm64 go vet -v ./...

      - name: Examine source code for Windows ARM
        run: GOOS=windows GOARCH=arm64 go vet -v ./...

      - name: Gosec security scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Test
        if: github.event_name == 'push'
        run: go test -v -cover -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: pilinux/logrus
